server.port=8081

# Para o Chat
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=llama3

# Para o Embedding (Vetorização)
langchain4j.ollama.embedding-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=phi3
langchain4j.hugging-face.embedding-model.access-token=${HF_TOKEN}
langchain4j.ollama.timeout=PT60S