langchain4j.ollama.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=llama3
langchain4j.open-ai.embedding-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.embedding-model.model-name=text-embedding-ada-002
langchain4j.ollama.timeout=PT60S